### ISSUE TITLE
3.0.1在Arduino IDE 2.3.3上编译出错

### ISSUE THREAD

**Issue by SSM5211314** [sprlightning/RF-Master#5]
`In file included from c:\Users\1\Documents\Arduino\libraries\ESPAsyncWebSrv\src\WebAuthentication.cpp:21:
c:\Users\1\Documents\Arduino\libraries\ESPAsyncWebSrv\src\WebAuthentication.h:27:51: error: missing binary operator before token "("
   27 | #if ESP_ARDUINO_VERSION >= ESP_ARDUINO_VERSION_VAL(3, 0, 0)
      |                                                   ^
In file included from c:\Users\1\Documents\Arduino\libraries\ESPAsyncWebSrv\src\WebRequest.cpp:23:
c:\Users\1\Documents\Arduino\libraries\ESPAsyncWebSrv\src\WebAuthentication.h:27:51: error: missing binary operator before token "("
   27 | #if ESP_ARDUINO_VERSION >= ESP_ARDUINO_VERSION_VAL(3, 0, 0)
      |                                                   ^

exit status 1

Compilation error: exit status 1`

**Comment by sprlightning** [comment]
去lib文件夹安装ESPAsyncWebServer库，详细内容看首页readme

**Comment by SSM5211314** [comment]
谢谢，编译问题已解决，但是烧录进去之后一上电就自动按上键，之前用2.9.a固件没问题，用的是射频管家（一板多用）单面焊接优化版:https://oshwhub.com/server1/ye-pin-guan-jia-yi-ban-duo-yong，是PCB不兼容嘛

**Comment by SSM5211314** [comment]
自动按上键已解决，方法是手动拉高GPIO0，然后操作下键和确认键来选择设备初始化，初始化之后问题解决

**Comment by sprlightning** [comment]
不太可能是硬件版本的是，PCB按键逻辑是一样的。但是软件也没问题。倒像是gpio0的上拉电阻没上拉。gpio0空闲状态应该是被上拉的，按键按下去是下拉。可以试试重刷程序。检查gpio0（12号脚）连接情况



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年09月21日 10:52 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [sprlightning/RF-Master] 3.0.1在Arduino IDE 2.3.3上编译出错 (Issue #5) |

谢谢，编译问题已解决，但是烧录进去之后一上电就自动按上键，之前用2.9.a固件没问题，用的是射频管家（一板多用）单面焊接优化版:https://oshwhub.com/server1/ye-pin-guan-jia-yi-ban-duo-yong，是PCB不兼容嘛
